{{- if and .Values.slackNotifier.enabled (not .Values.slackNotifier.config.existingSecret) .Values.slackNotifier.config.slackWebhookUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh.fullname" . }}-slack-notifier
  labels:
    app: {{ include "wazuh.fullname" . }}-slack-notifier
type: Opaque
stringData:
  {{ .Values.slackNotifier.config.secretKey }}: {{ .Values.slackNotifier.config.slackWebhookUrl | quote }}
{{- end }}
