{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
metadata:
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- tpl (toYaml . | nindent 4) $ }}
  {{- end }}
  name: {{ include "wazuh.serviceAccountName" . }}
  namespace: {{ include "wazuh.namespace" . }}
{{- end }}
