apiVersion: v2
name: wazuh
description: Wazuh is a security information and event management (SIEM) solution that provides security monitoring, threat detection, and incident response capabilities.
type: application
appVersion: 4.11.1
version: 0.0.51
home: https://wazuh.com/
sources:
  - https://github.com/antero-software/wazuh-helm-chart
maintainers:
  - name: ilker
    email: ilker@antero.com.au
    url: https://github.com/ilkerispir
icon: https://antero-software.github.io/wazuh-helm-chart/images/icon.png
keywords:
  - security
  - information
  - threat
  - management
  - wazuh
  - opendistro
  - elasticsearch
dependencies:
  - name: cert-manager
    version: 1.17.1
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
annotations:
  artifacthub.io/category: security
  artifacthub.io/changes: |
    - kind: changed
      description: Update Wazuh to 4.11.1
  # artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/links: |
    - name: application source
      url: https://github.com/wazuh/wazuh
    - name: kustomize source
      url: https://github.com/wazuh/wazuh-kubernetes
  artifacthub.io/prerelease: "false"
  artifacthub.io/screenshots: |
    - title: Home Page
      url: https://antero-software.github.io/wazuh-helm-chart/images/dashboard.png
    - title: Agent Deployment
      url: https://antero-software.github.io/wazuh-helm-chart/images/agent-deploy.png
    - title: Threat Hunting
      url: https://antero-software.github.io/wazuh-helm-chart/images/threat-hunting.png
