apiVersion: v2
name: wazuh
description: Wazuh is a security information and event management (SIEM) solution that provides security monitoring, threat detection, and incident response capabilities.
type: application
appVersion: 4.11.1
version: 0.0.1
home: https://wazuh.com/
sources:
  - https://github.com/antero-software/wazuh-helm-chart
dependencies:
  - name: cert-manager
    version: 1.17.1
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
