cert-manager:
  enabled: false

nameOverride: null
fullnameOverride: null

imagePullSecrets: []

serviceAccount:
  create: false
  name: wazuh
  automountServiceAccountToken: false
  annotations: {}

# Kibana for elasticsearch with Wazuh plugins pre-installed
dashboard:
  replicas: 2

  annotations: {}
  podAnnotations: {}

  images:
    repository: wazuh/wazuh-dashboard
    tag: "4.11.1"
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  
  pdb:
    enabled: false
    maxUnavailable: 1
  
  # Will be implemented on Wazuh v5.0.0
  # readinessProbe: {}

  securityContext: {}

  networkPolicy:
    enabled: true

  # with this you will be able to access kibana on http port instead of https
  # if you use Ambassador edgestack this is necessary becasue
  # with `true` route will close unexpectedly
  # when accessing via ambassador external url
  enable_ssl: false

  service:
    annotations: {}
    httpPort: 5601
    type: ClusterIP
  
  cred:
    existingSecret: ""
    username: "kibanaserver"
    password: "kibanaserver"
  
  config: |
    {{- include "wazuh.dashboard.config" . | indent 2 -}}

  env:
    LOG_LEVEL: "error"

  ingress:
    enabled: false
    ingressClassName: ""
    annotations: {}
    labels: {}
    hosts:
      - host: wazuh.example.com
        paths:
          - path: /
          # pathType: Prefix
    tls: []
    # - secretName: wazuh-tls
    #   hosts:
    #     - wazuh.example.com


indexer:
  replicas: 3

  annotations: {}
  podAnnotations: {}

  service:
    annotations: {}
    httpPort: 9200
    nodes: 9300
    metrics: 9600

  updateStrategy: RollingUpdate
  
  images:
    repository: wazuh/wazuh-indexer
    tag: "4.11.1"
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 2Gi
  
  pdb:
    enabled: false
    maxUnavailable: 1

  # Will be implemented on Wazuh v5.0.0
  # readinessProbe: {}

  securityContext: {}

  networkPolicy:
    enabled: true

  initContainers:
    volumeMountHack:
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi
      securityContext: {}
    increaseTheVmMaxMapCount:
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi
      securityContext:
        privileged: true

  config:
    opensearch: |-
      {{- include "wazuh.indexer.opensearchConfig" . | indent 2 -}}
    internalUsers: |-
      _meta:
        type: "internalusers"
        config_version: 2
      admin:
        hash: "$2y$12$K/SpwjtB.wOHJ/Nc6GVRDuc1h0rM1DfvziFRNPtk27P.c4yDr9njO"
        reserved: true
        backend_roles:
          - "admin"
        description: "Admin user"
    security: |-
      _meta:
        type: "config"
        config_version: 2

      config:
        dynamic:
          http:
            anonymous_auth_enabled: false
            xff:
              enabled: false
              internalProxies: '192\.168\.0\.10|192\.168\.0\.11'
          authc:
            kerberos_auth_domain:
              http_enabled: false
              transport_enabled: false
              order: 6
              http_authenticator:
                type: kerberos
                challenge: true
                config:
                  krb_debug: false
                  strip_realm_from_principal: true
              authentication_backend:
                type: noop
            basic_internal_auth_domain:
              description: "Authenticate via HTTP Basic against internal users database"
              http_enabled: true
              transport_enabled: true
              order: 4
              http_authenticator:
                type: basic
                challenge: true
              authentication_backend:
                type: intern
            proxy_auth_domain:
              description: "Authenticate via proxy"
              http_enabled: false
              transport_enabled: false
              order: 3
              http_authenticator:
                type: proxy
                challenge: false
                config:
                  user_header: "x-proxy-user"
                  roles_header: "x-proxy-roles"
              authentication_backend:
                type: noop
            jwt_auth_domain:
              description: "Authenticate via Json Web Token"
              http_enabled: false
              transport_enabled: false
              order: 0
              http_authenticator:
                type: jwt
                challenge: false
                config:
                  signing_key: "base64 encoded HMAC key or public RSA/ECDSA pem key"
                  jwt_header: "Authorization"
                  jwt_url_parameter: null
                  jwt_clock_skew_tolerance_seconds: 30
                  roles_key: null
                  subject_key: null
              authentication_backend:
                type: noop
            clientcert_auth_domain:
              description: "Authenticate via SSL client certificates"
              http_enabled: false
              transport_enabled: false
              order: 2
              http_authenticator:
                type: clientcert
                config:
                  username_attribute: cn
                challenge: false
              authentication_backend:
                type: noop
            ldap:
              description: "Authenticate via LDAP or Active Directory"
              http_enabled: false
              transport_enabled: false
              order: 5
              http_authenticator:
                type: basic
                challenge: false
              authentication_backend:
                type: ldap
                config:
                  enable_ssl: false
                  enable_start_tls: false
                  enable_ssl_client_auth: false
                  verify_hostnames: true
                  hosts:
                  - localhost:8389
                  bind_dn: null
                  password: null
                  userbase: 'ou=people,dc=example,dc=com'
                  usersearch: '(sAMAccountName={0})'
                  username_attribute: null
          authz:
            roles_from_myldap:
              description: "Authorize via LDAP or Active Directory"
              http_enabled: false
              transport_enabled: false
              authorization_backend:
                type: ldap
                config:
                  enable_ssl: false
                  enable_start_tls: false
                  enable_ssl_client_auth: false
                  verify_hostnames: true
                  hosts:
                  - localhost:8389
                  bind_dn: null
                  password: null
                  rolebase: 'ou=groups,dc=example,dc=com'
                  rolesearch: '(member={0})'
                  userroleattribute: null
                  userrolename: disabled
                  rolename: cn
                  resolve_nested_roles: true
                  userbase: 'ou=people,dc=example,dc=com'
                  usersearch: '(uid={0})'
            roles_from_another_ldap:
              description: "Authorize via another Active Directory"
              http_enabled: false
              transport_enabled: false
              authorization_backend:
                type: ldap

  env:
    OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
    OPENSEARCH_JAVA_ADD_OPTS: "-Djava.security.manager="
    CLUSTER_NAME: "wazuh"
    NETWORK_HOST: "0.0.0.0"
    DISABLE_INSTALL_DEMO_CONFIG: "true"

  # If defined, storageClassName: <storageClass>
  # If set to "-", storageClassName: "", which disables dynamic provisioning
  # If undefined (the default) or set to null, no storageClassName spec is
  #   set, choosing the default provisioner.
  storageClass: null
  storageSize: 50Gi

  cred:
    existingSecret: ""
    username: "admin"
    password: "SecretPassword"    


wazuh:
  key: "c98b62a9b6169ac5f67dae55ae4a9088"
  images:
    repository: wazuh/wazuh-manager
    tag: "4.11.1"
    pullSecret: regcred

  # Will be implemented on Wazuh v5.0.0
  # readinessProbe: {}

  env:
    FILEBEAT_SSL_VERIFICATION_MODE: full

  service:
    annotations: {}
    port: 1516

  apiCred:
    # 3 Options:
    # 1. Set existing secret name
    # 2. Set username and password manually
    # 3. Let secret be generated automatically (all empty)
    existingSecret: ""
    username: "wazuh-wui"
    # The password must have a length between 8 and 64 characters and contain at least one upper and lower case letter, a number, and a symbol(.*+?-).
    password: "MyS3cr37P450r.*-"
  authd:
    existingSecret: ""
    pass: "password"
  
  initContainer:
    resources: 
      limits:
        memory: 32Mi
      requests:
        cpu: 5m
        memory: 16Mi

  extraRules: |
    {{- include "wazuh.extra_rules" . | indent 2 -}}

  master:
    annotations: {}
    podAnnotations: {}

    service:
      type: ClusterIP
      annotations: {}
      ports:
        registration: 1515
        api: 55000

    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    
    networkPolicy:
      enabled: true
    
    storageClass: null
    storageSize: 50Gi

    ingress:
      agentRegistration:
        enabled: false
        ingressClassName: ""
        annotations: {}
        labels: {}
        hosts:
          - host: wazuh-agent-register.example.com
            paths:
              - path: /
              # pathType: Prefix
        tls: []
        # - secretName: wazuh-tls
        #   hosts:
        #     - wazuh.example.com

    conf: |
      {{- include "wazuh.master.conf" . | indent 2 -}}
    # To be appended to the master.conf
    extraConf: ""
    localInternalOptions: |
      {{- include "wazuh.master.local_internal_options" . | indent 2 -}}

  worker:
    replicas: 2

    annotations: {}
    podAnnotations: {}

    service:
      type: ClusterIP
      annotations: {}
      ports:
        agentEvents: 1514

    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    
    pdb:
      enabled: false
      maxUnavailable: 1
    
    networkPolicy:
      enabled: true

    storageClass: null
    storageSize: 50Gi

    ingress:
      enabled: false
      ingressClassName: ""
      annotations: {}
      labels: {}
      hosts:
        - host: wazuh-agent-events.example.com
          paths:
            - path: /
            # pathType: Prefix
      tls: []
      # - secretName: wazuh-tls
      #   hosts:
      #     - wazuh.example.com
    
    conf: |
      {{- include "wazuh.worker.conf" . | indent 2 -}}
    # To be appended to the worker.conf
    extraConf: ""
    localInternalOptions: |
      {{- include "wazuh.worker.local_internal_options" . | indent 2 -}}
