apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wazuh.fullname" . }}-manager-config
data:
  script.sh: |-
    #!/bin/sh

    echo "[init] Starting init config setup for $(hostname)"

    # Only copy config if it doesn't already exist (prevents overwriting UI changes)
    if [ ! -f /var/ossec/etc/ossec.conf ]; then
      echo "[init] ossec.conf not found in /var/ossec/etc, copying default from /ossec.conf"
      cp /ossec.conf /var/ossec/etc/ossec.conf
      node_index=${HOSTNAME##*-}
      sed -i "s/___INDEX___/$node_index/g" /var/ossec/etc/ossec.conf
    else
      echo "[init] ossec.conf already exists in /var/ossec/etc, skipping copy"
    fi

    # Ensure shared directory exists and has correct permissions
    mkdir -p /var/ossec/etc/shared
    chown -R root:wazuh /var/ossec/etc/shared
    chmod -R 775 /var/ossec/etc/shared

    # Ensure base /etc directory is writable by ossec user
    chown root:wazuh /var/ossec/etc
    chmod 770 /var/ossec/etc

    # Fix config ownership and permissions to allow UI to take backups
    chown ossec:ossec /var/ossec/etc/ossec.conf
    chmod 660 /var/ossec/etc/ossec.conf

    # Create empty agent-template.conf if it doesn't exist
    TEMPLATE_FILE="/var/ossec/etc/shared/agent-template.conf"
    if [ ! -f "$TEMPLATE_FILE" ]; then
      echo '<agent_config></agent_config>' > "$TEMPLATE_FILE"
      chown root:wazuh "$TEMPLATE_FILE"
      chmod 664 "$TEMPLATE_FILE"
    fi
  master.conf: |
    {{- tpl .Values.wazuh.master.conf . | indent 2 }}
  master_local_internal_options.conf: |
    {{- tpl .Values.wazuh.master.localInternalOptions . | indent 2 }}
  worker.conf: |
    {{- tpl .Values.wazuh.worker.conf . | indent 2 }}
  worker_local_internal_options.conf: |
    {{- tpl .Values.wazuh.worker.localInternalOptions . | indent 2 }}