apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "wazuh.fullname" . }}-indexer
  annotations:
    {{- toYaml .Values.indexer.annotations | nindent 4 }}
  name: {{ include "wazuh.fullname" . }}-indexer-config
data:
  internal_users.yml: |
{{ .Values.indexer.config.internalUsers | nindent 4 }}
  opensearch.yml: |
{{ tpl .Values.indexer.config.opensearch . | nindent 4 }}
  config.yml: |
{{ tpl .Values.indexer.config.security . | nindent 4 }}